services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SmthDiff\ContaoSkeletonBundle\:
    resource: ../../../src
    exclude: ../../../src/{Entity,Migrations,Resources,Tests}

  SmthDiff\ContaoSkeletonBundle\Controller\:
    resource: ../../../src/Controller
    public: true
